import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
const tokens=JSON.parse(await readFile(new URL('../../../tokens/responsive.json',import.meta.url),'utf8'));
const base=process.env.PROTOTYPE_URL || 'http://127.0.0.1:4180';
const output='/tmp/viptv-responsive-review';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--renderer-process-limit=1']});
const page=await browser.newPage();
const errors=[]; const results=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('requestfailed',r=>errors.push(`${r.method()} ${r.url()}: ${r.failure()?.errorText}`));
async function check(name,fn){await fn();results.push(name);console.log(`PASS ${name}`)}
async function goto(query=''){await page.goto(`${base}/?${query}`);await page.getByRole('navigation',{name:'Main navigation'}).waitFor();}
async function nav(name){await page.getByRole('navigation').getByRole('button',{name,exact:true}).click();}
async function noOverflow(){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page has horizontal overflow');}
async function close(){await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});}
try {
 await check('Rust fixture initializes and landscape images load',async()=>{await goto();await page.locator('.feature-art img').evaluate(img=>img.decode());assert.equal(await page.locator('.feature h1').textContent(),'The quiet earth');assert(await page.locator('.feature-art img').evaluate(img=>img.naturalWidth>img.naturalHeight));});
 for(const [width,height] of [[320,568],[390,844],[768,1024],[1024,600],[1440,900],[2560,1080],[900,400]])for(const variant of ['A','B','C'])for(const theme of ['dark','oled']){
  await check(`layout ${width}×${height} ${variant} ${theme}`,async()=>{await page.setViewportSize({width,height});await goto(`variant=${variant}&theme=${theme}`);await noOverflow();const colors=await page.locator('html').evaluate((element,theme)=>Object.fromEntries(Object.keys(theme).map(name=>[name,getComputedStyle(element).getPropertyValue(`--${name}`).trim()])),tokens.themes[theme]);assert.deepEqual(colors,tokens.themes[theme]);const art=page.locator('.feature-art');assert.equal(await art.evaluate(e=>getComputedStyle(e).backgroundImage),'none');const geometry=await page.locator('.card-art').first().boundingBox();assert(Math.abs(geometry.width/geometry.height-16/9)<.02);if(theme==='oled')assert.equal(await page.locator('html').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(0, 0, 0)');if(variant==='A'&&theme==='oled'&&[390,1440,2560].includes(width))await page.screenshot({path:`${output}/${width}-oled.png`});});
 }
 await page.setViewportSize({width:390,height:844});await goto();
 await check('Profile selection ring is concentric with avatar',async()=>{await nav('Settings');await page.getByRole('button',{name:'Switch profile',exact:true}).click();const avatar=page.locator('.profile-tile[aria-pressed=true] .avatar');assert.equal(await avatar.evaluate(e=>getComputedStyle(e).outlineWidth),'3px');assert.equal(await avatar.evaluate(e=>getComputedStyle(e).borderRadius),'50%');await page.screenshot({path:`output/profile.png`.replace('output',output)});await page.getByRole('button',{name:'Kids Kids profile'}).click();await page.getByRole('button',{name:'Switch profile',exact:true}).click();assert.equal(await page.locator('.profile-tile[aria-pressed=true] strong').textContent(),'Kids');});
 await check('Search, empty result, detail and source loading/cancellation',async()=>{await nav('Search');await page.getByRole('searchbox').fill('north');await page.getByRole('button',{name:'Details: North of nowhere',exact:true}).click();await page.getByRole('button',{name:'Choose source',exact:true}).click();await page.locator('.menu-list button').first().click();await page.getByRole('heading',{name:'Opening your source…'}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.waitForTimeout(1000);assert.equal(await page.locator('dialog[open]').count(),0);await nav('Search');await page.getByRole('searchbox').fill('zzzz');await page.getByRole('heading',{name:'No titles found'}).waitFor();});
 await check('Web Vizio handoff makes no direct TV connection promise',async()=>{await page.getByRole('button',{name:'Watch on TV',exact:true}).first().click();await page.getByRole('heading',{name:'Connect from the viptv app'}).waitFor();assert.equal(await page.getByRole('textbox',{name:'TV IP address'}).count(),0);await close();});
 await check('OLED settings updates canvas without changing card geometry',async()=>{await nav('Settings');await page.getByRole('button',{name:/OLED black/}).click();assert.equal(await page.locator('html').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(0, 0, 0)');await noOverflow();});
 await goto('platform=tauri');
 await check('Native Vizio pairing, rejected PIN, launch failure and retry',async()=>{await page.getByRole('button',{name:'Watch on TV',exact:true}).click();await page.getByRole('textbox',{name:'TV IP address'}).fill('192.168.1.50');await page.getByRole('button',{name:'Pair TV',exact:true}).click();await page.getByRole('textbox',{name:'TV pairing code'}).fill('0000');await page.getByRole('button',{name:'Confirm pairing',exact:true}).click();await page.getByRole('alert').filter({hasText:'The TV rejected that code'}).waitFor();await page.getByRole('textbox',{name:'TV pairing code'}).fill('1234');await page.getByRole('button',{name:'Confirm pairing',exact:true}).click();await page.getByRole('checkbox',{name:'Simulate launch failure'}).check();await page.getByRole('button',{name:'Open viptv on TV',exact:true}).click();await page.getByRole('heading',{name:'Your TV didn’t confirm the launch'}).waitFor();await page.getByRole('button',{name:'Back to TV'}).click();await page.getByRole('checkbox',{name:'Simulate launch failure'}).uncheck();await page.getByRole('button',{name:'Open viptv on TV',exact:true}).click();await page.getByText('The TV accepted the request.',{exact:false}).waitFor();await noOverflow();await page.screenshot({path:`${output}/vizio-mobile.png`});await page.getByRole('button',{name:'TV OK',exact:true}).click();await close();assert.equal(await page.getByRole('button',{name:'Living room',exact:true}).count(),1);});
 await check('Player preview, keyboard seeking, captions and Escape return',async()=>{await page.locator('.feature .primary').click();await page.locator('.menu-list button').first().click();await page.getByText('PLAYBACK DESIGN PREVIEW',{exact:true}).waitFor();await page.getByRole('button',{name:'Subtitles',exact:true}).click();await page.locator('.caption').waitFor();await page.getByRole('button',{name:'Pause',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('slider',{name:'Playback position'}).inputValue(),'1250');await page.keyboard.press('Escape');await page.locator('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.feature .primary').evaluate(e=>e===document.activeElement),true);});
 await check('Reduced motion and local carousel boundary',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.card-hit').first().focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(200);await page.keyboard.up('ArrowRight');assert.equal(await page.locator('.shelf').first().locator('.card-hit').nth(1).evaluate(e=>e===document.activeElement),true);await noOverflow();});

 await check('Source failure remains recoverable with visible progress',async()=>{await goto();await page.locator('.study-tools summary').click();await page.getByRole('combobox',{name:'Preview state'}).selectOption('playback-error');await page.locator('.study-tools summary').click();await page.locator('.feature .primary').click();await page.locator('.menu-list button').first().click();await page.getByRole('heading',{name:'This source couldn’t start'}).waitFor();await page.getByRole('button',{name:'Choose another source'}).click();await page.locator('.menu-list button').first().waitFor();await close();});
 await check('Context menu shortcut and next episode identity',async()=>{await goto();await page.locator('.card-hit').first().focus();await page.keyboard.press('Shift+F10');await page.getByRole('dialog',{name:'Title actions'}).waitFor();await close();await page.locator('.feature .primary').click();await page.locator('.menu-list button').first().click();await page.getByRole('button',{name:'Next episode',exact:true}).click();await page.getByRole('button',{name:'Play next episode',exact:true}).click();await page.getByRole('dialog',{name:'Choose a source'}).getByText('S1 E4 · A different sky',{exact:true}).waitFor();await close();});
 for(const size of [{width:320,height:568},{width:900,height:400},{width:1440,height:900}])await check(`All study routes fit ${size.width}×${size.height}`,async()=>{await page.setViewportSize(size);await goto('theme=oled');for(const route of ['Search','Live TV','Library','Settings']){await nav(route);await noOverflow();assert.equal(await page.locator('main h1').count(),1);}await page.getByRole('button',{name:'Switch profile',exact:true}).click();await noOverflow();});
 await check('Loading, empty, failure and missing art states fit phone',async()=>{await page.setViewportSize({width:320,height:568});await goto();await page.locator('.study-tools summary').click();for(const state of ['loading','empty','error','no-art']){await page.getByRole('combobox',{name:'Preview state'}).selectOption(state);await noOverflow();}assert.equal(await page.locator('.feature-art img:visible').count(),0);});
 assert.deepEqual(errors,[]);await writeFile(`${output}/results.json`,JSON.stringify({passed:results.length,results,errors},null,2));console.log(`PASS ${results.length} checks; images and result JSON: ${output}`);
} finally {await browser.close();}
